version: '3.8'
services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: ride_the_wave_dynamodb
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data

volumes:
  dynamodb_data:
